'''
Created on 18.5.2014

@author: Morzeux
'''

def generate_triangle(num):
    """ Generates triangle numbers. """
    return num * (num + 1) / 2

def generate_pentagonal(num):
    """ Generates pentagonal numbers. """
    return num * (3 * num - 1) / 2

def generate_hexagonal(num):
    """ Generates hexagonal numbers. """
    return num * (2 * num - 1)

def problem(num=100000, maximum=40755):
    """
    Triangle, pentagonal, and hexagonal numbers are generated by the following
    formulae:

        Triangle         Tn=n(n+1)/2        1, 3, 6, 10, 15, ...
        Pentagonal       Pn=n(3n-1)/2       1, 5, 12, 22, 35, ...
        Hexagonal        Hn=n(2n-1)         1, 6, 15, 28, 45, ...
        It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
    """
    triangles = [generate_triangle(i) for i in range(1, num + 1)]
    pentagonals = set([generate_pentagonal(i) for i in range(1, num + 1)])
    hexagonals = set([generate_hexagonal(i) for i in range(1, num + 1)])

    for i in triangles:
        if i in pentagonals and i in hexagonals and i > maximum:
            return i

    return problem(num * 10, maximum)
